// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXWyMbBnjzSVtnDoDgWGuebgazXoO0818',
    appId: '1:950681020352:web:b08b506bdc382447b0ca25',
    messagingSenderId: '950681020352',
    projectId: 'gonest-5e2ae',
    authDomain: 'gonest-5e2ae.firebaseapp.com',
    storageBucket: 'gonest-5e2ae.firebasestorage.app',
    measurementId: 'G-SHTG933MY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuNn01tfr5rcd-MsYkzGDo8Zvk7rbrN_w',
    appId: '1:950681020352:android:d0418eef522f58c7b0ca25',
    messagingSenderId: '950681020352',
    projectId: 'gonest-5e2ae',
    storageBucket: 'gonest-5e2ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6t6NIgqxQm1cS7bTxByfFVWTpQxWUaZc',
    appId: '1:950681020352:ios:d41d3d940d7cbfeab0ca25',
    messagingSenderId: '950681020352',
    projectId: 'gonest-5e2ae',
    storageBucket: 'gonest-5e2ae.firebasestorage.app',
    iosBundleId: 'com.example.gonest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6t6NIgqxQm1cS7bTxByfFVWTpQxWUaZc',
    appId: '1:950681020352:ios:d41d3d940d7cbfeab0ca25',
    messagingSenderId: '950681020352',
    projectId: 'gonest-5e2ae',
    storageBucket: 'gonest-5e2ae.firebasestorage.app',
    iosBundleId: 'com.example.gonest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXWyMbBnjzSVtnDoDgWGuebgazXoO0818',
    appId: '1:950681020352:web:0e06ea27de41157ab0ca25',
    messagingSenderId: '950681020352',
    projectId: 'gonest-5e2ae',
    authDomain: 'gonest-5e2ae.firebaseapp.com',
    storageBucket: 'gonest-5e2ae.firebasestorage.app',
    measurementId: 'G-TPCQL3ZXQD',
  );
}
